package com.williamzabot.notascoloridas.ui.colors

const val COR_PADRAO = "brancofundo"
const val AZUL = "azul"
const val AZUL_FUNDO = "azulfundo"
const val BRANCO = "branco"
const val VERMELHO = "vermelho"
const val VERMELHO_FUNDO = "vermelhofundo"
const val VERDE = "verde"
const val VERDE_FUNDO = "verdefundo"
const val AMARELO = "amarelo"
const val AMARELO_FUNDO = "amarelofundo"
const val LILAS = "lilas"
const val LILAS_FUNDO = "lilasfundo"
const val CINZA = "cinza"
const val CINZA_FUNDO = "cinzafundo"
const val MARROM = "marrom"
const val MARROM_FUNDO = "marromfundo"
const val ROXO = "roxo"
const val ROXO_FUNDO = "roxofundo"